model_list:
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
      api_key: os.environ/ANTHROPIC_API_KEY

guardrails:

  - guardrail_name: "external-tool-evaluator"
    litellm_params:
      guardrail: external_hook_evaluate.ExternalHookEvaluateGuardrail
      mode: post_call
      default_on: true
      api_base: "http://localhost:8000"
      api_key: "veto_2REJ31PCnoPwQB0GkgsJonoLwro6xAA1T5S0O2nfcuE"

environment_variables:
  UI_USERNAME: "admin"
  UI_PASSWORD: "admin"

general_settings:
  master_key: sk-test-master-key
  database_url: "postgresql://postgres:testpass@localhost:5433/litellm"
  store_model_in_db: true
  store_prompts_in_spend_logs: true
